import type { Food } from "./types";

export const fallbackCategories = [
  "All",
  "Burgers",
  "Pizza",
  "Asian",
  "Salads",
  "Desserts",
  "Drinks",
];

export const fallbackFoods: Food[] = [
  {
    _id: "food-1",
    name: "Classic Smash Burger",
    description: "Double-smashed beef patties with melted American cheese, caramelized onions, pickles, and our secret sauce on a toasted brioche bun.",
    price: 350,
    category: "Burgers",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=400&fit=crop",
    available: true,
    rating: 4.8,
    reviews: 234,
    tags: ["popular", "bestseller"],
    ingredients: ["Beef Patty", "American Cheese", "Brioche Bun", "Pickles", "Caramelized Onions", "Secret Sauce"],
    restaurantName: "Fresh Bites Rangunia",
    location: "Rangunia, Chittagong",
  },
  {
    _id: "food-2",
    name: "Bacon BBQ Burger",
    description: "Juicy beef patty topped with crispy bacon, cheddar cheese, BBQ sauce, lettuce, and tomato on a sesame bun.",
    price: 450,
    category: "Burgers",
    image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&h=400&fit=crop",
    available: true,
    rating: 4.6,
    reviews: 189,
    tags: ["trending"],
    ingredients: ["Beef Patty", "Bacon", "Cheddar Cheese", "BBQ Sauce", "Lettuce", "Tomato"],
    restaurantName: "Fresh Bites Rangunia",
    location: "Rangunia, Chittagong",
  },
  {
    _id: "food-3",
    name: "Margherita Pizza",
    description: "Traditional Neapolitan pizza with San Marzano tomato sauce, fresh mozzarella, basil, and extra virgin olive oil on a wood-fired crust.",
    price: 600,
    category: "Pizza",
    image: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&h=400&fit=crop",
    available: true,
    rating: 4.9,
    reviews: 312,
    tags: ["popular", "top-rated"],
    ingredients: ["Pizza Dough", "San Marzano Tomatoes", "Fresh Mozzarella", "Basil", "Olive Oil"],
    restaurantName: "Fresh Bites Rangunia",
    location: "Rangunia, Chittagong",
  },
  {
    _id: "food-4",
    name: "Pepperoni Supreme Pizza",
    description: "Loaded with premium pepperoni, mozzarella, parmesan, and a hint of chili flakes on our signature thin crust.",
    price: 750,
    category: "Pizza",
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&h=400&fit=crop",
    available: true,
    rating: 4.7,
    reviews: 276,
    tags: ["popular"],
    ingredients: ["Pizza Dough", "Mozzarella", "Pepperoni", "Parmesan", "Chili Flakes", "Tomato Sauce"],
    restaurantName: "Fresh Bites Rangunia",
    location: "Rangunia, Chittagong",
  },
  {
    _id: "food-5",
    name: "Pad Thai Noodles",
    description: "Stir-fried rice noodles with shrimp, tofu, bean sprouts, peanuts, and tamarind sauce, garnished with lime and cilantro.",
    price: 350,
    category: "Asian",
    image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&h=400&fit=crop",
    available: true,
    rating: 4.5,
    reviews: 198,
    tags: ["trending"],
    ingredients: ["Rice Noodles", "Shrimp", "Tofu", "Bean Sprouts", "Peanuts", "Tamarind Sauce"],
    restaurantName: "Fresh Bites Rangunia",
    location: "Rangunia, Chittagong",
  },
  {
    _id: "food-6",
    name: "Spicy Tonkotsu Ramen",
    description: "Rich tonkotsu broth with tender chashu, soft-boiled egg, bamboo shoots, nori, and spring onions with custom chili oil.",
    price: 400,
    category: "Asian",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop",
    available: true,
    rating: 4.8,
    reviews: 245,
    tags: ["top-rated", "trending"],
    ingredients: ["Tonkotsu Broth", "Chashu Pork", "Ramen Noodles", "Soft-Boiled Egg", "Nori", "Bamboo Shoots"],
    restaurantName: "Fresh Bites Rangunia",
    location: "Rangunia, Chittagong",
  },
  {
    _id: "food-7",
    name: "Mediterranean Salad Bowl",
    description: "Fluffy quinoa with roasted chickpeas, crisp cucumbers, cherry tomatoes, kalamata olives, and fresh feta cheese with herb vinaigrette.",
    price: 250,
    category: "Salads",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop",
    available: true,
    rating: 4.4,
    reviews: 143,
    tags: ["healthy"],
    ingredients: ["Quinoa", "Chickpeas", "Cherry Tomatoes", "Cucumber", "Feta Cheese", "Olives"],
    restaurantName: "Fresh Bites Rangunia",
    location: "Rangunia, Chittagong",
  },
  {
    _id: "food-8",
    name: "Fresh Caesar Salad",
    description: "Crisp romaine lettuce, shaved parmesan, house garlic croutons, and creamy Caesar dressing.",
    price: 250,
    category: "Salads",
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=600&h=400&fit=crop",
    available: true,
    rating: 4.3,
    reviews: 112,
    tags: ["healthy"],
    ingredients: ["Romaine Lettuce", "Parmesan", "Croutons", "Caesar Dressing"],
    restaurantName: "Fresh Bites Rangunia",
    location: "Rangunia, Chittagong",
  },
  {
    _id: "food-9",
    name: "Classic Italian Tiramisu",
    description: "Layers of espresso-soaked ladyfingers, velvety mascarpone cream, and rich Belgian cocoa powder.",
    price: 200,
    category: "Desserts",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&h=400&fit=crop",
    available: true,
    rating: 4.9,
    reviews: 287,
    tags: ["top-rated", "bestseller"],
    ingredients: ["Mascarpone", "Ladyfingers", "Espresso", "Cocoa Powder"],
    restaurantName: "Fresh Bites Rangunia",
    location: "Rangunia, Chittagong",
  },
  {
    _id: "food-10",
    name: "Chocolate Lava Cake",
    description: "Warm, decadent dark chocolate cake with a molten center, served with vanilla bean ice cream.",
    price: 200,
    category: "Desserts",
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=600&h=400&fit=crop",
    available: true,
    rating: 4.8,
    reviews: 256,
    tags: ["trending"],
    ingredients: ["Dark Chocolate", "Butter", "Eggs", "Vanilla Ice Cream"],
    restaurantName: "Fresh Bites Rangunia",
    location: "Rangunia, Chittagong",
  },
  {
    _id: "food-11",
    name: "Fresh Mango Smoothie",
    description: "Refreshing blend of ripe tropical mangoes, chilled yogurt, pure honey, and a touch of coconut milk.",
    price: 150,
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=600&h=400&fit=crop",
    available: true,
    rating: 4.8,
    reviews: 165,
    tags: ["popular"],
    ingredients: ["Fresh Mango", "Yogurt", "Honey", "Coconut Milk"],
    restaurantName: "Fresh Bites Rangunia",
    location: "Rangunia, Chittagong",
  },
  {
    _id: "food-12",
    name: "Iced Caramel Macchiato",
    description: "Freshly brewed espresso poured over cold milk and vanilla syrup, drizzled with buttery caramel sauce.",
    price: 150,
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&h=400&fit=crop",
    available: true,
    rating: 4.7,
    reviews: 142,
    tags: ["trending"],
    ingredients: ["Espresso", "Milk", "Vanilla Syrup", "Caramel Sauce"],
    restaurantName: "Fresh Bites Rangunia",
    location: "Rangunia, Chittagong",
  },
];
